### PR TITLE
Bug fixing

### LINKED ISSUE #8: ensure that id and command list lengths are the same in joint commands.
Currently, lists are zipped together. Zip fails silently if the lists are not the same length.

Some commands where this is an issue:

set_command_position, set_joint_velocity, set_joint_effort in vrep_interface.py

For example this snippet fails silently if the lists for ids and commands doesn't have the same length.

```python
    def set_command_position(self, ids, commands, send=False):
        for i,c in zip(ids,commands):
            vrep.simxSetJointTargetPosition(self._sim_Client_ID, self.joint[i]['sim_handle'], c,
                                            vrep.simx_opmode_oneshot)
        if send:
            self.send_command()
```

### LINKED ISSUE #12: Duplicate key in dxl_control_table DXLPRO
The key L54_30_S500_R appears twice in the resolution dictionary for DXLPRO and with two different values.

### PR DESCRIPTION
**Pull request by TMengi**
Fixes #12 - replaced the duplicate key in DXLPRO.resolution with the correct motor type.

Added a check to close DXL ports in motion_manager

Fixes #8 - used asserts to check that the number of ids matches the number of commands when setting position, velocity, etc. Throws an exception if not the same length.

Relative imports changed in motion_manager. Not sure if this breaks things for other users but it works on my end.

Removed an unused import math.pi. It was used in a commented out ifmain section in motion_manager, so I replaced those with np.pi, which is also imported.

Edited the README to reflect some changes that were made elsewhere.

Removed the default value for ports in DxlOptions.__init__. We said during our last meeting that it is probably best to require the user to pass a port so that we don't try to write to some unknown device by accident.

### CODE REVIEW

**Comment by danielasun** [comment]
Is this for python2 or python 3?

**Comment by TMengi** [comment]
These are based on the master branch, python2

**Comment by danielasun** [comment]
Do we need to change from using absolute imports to relative imports? Also, I think I may have encountered some small bugs in the commit. Will look at that later today.

**Comment by TMengi** [comment]
Changed the imports from relative back to absolute. Seems to work the same on my end

**Comment by danielasun** [comment]
I added some unittests and checked out that everything is working on Linux.

**Pull request merged**
